### ISSUE TITLE
Add basic histograms

### ISSUE THREAD

**Issue by omri312** [CoronaHakab/CoronaHakabModel#142]
We should create A new module, fully separate from the whole simulation named MatrixAnalyzer.
It should be similar to the PopulationAnalyzer module described in: https://github.com/CoronaHakab/CoronaHakabModel/issues/140
It should contain:

היסטוגרמה של מספר קשרים כולל + ממוצע וחציון (מעגל ראשון כללי)

 - בהפרדה לסוגי קשרים
היסטוגרמה של מספר קשרי בית + ממוצע וחציון (מעגל ראשון בית)
היסטוגרמה של מספר קשרי עבודה + ממוצע וחציון
היסטוגרמה של מספר קשרי בית ספר + ממוצע וחציון
היסטוגרמה של מספר קשרי other + ממוצע וחציון

**Comment by tal-nc** [comment]
this information should also be extracted as a .csv file
