### ISSUE TITLE
Have a simple guide for working with git

### ISSUE THREAD

**Issue by omri312** [CoronaHakab/CoronaHakabModel#20]
In order to not waste time,
Make/find a simple guide of using git -

1. installing (git bash? other software?)
2. code viewing (only clone and run)
3. code editing (branch opening, pushing, rebasing, PR)

**Comment by bentheiii** [comment]
Here's something I wrote for our small team a while back, you can use it as a starting point

[How to set up a git environment.docx](https://github.com/CoronaHakab/CoronaHakabModel/files/4364854/How.to.set.up.a.git.environment.docx)
[How to set up a git environment.pdf](https://github.com/CoronaHakab/CoronaHakabModel/files/4364855/How.to.set.up.a.git.environment.pdf)

**Comment by bentheiii** [comment]
updated the guide with fork/branch instructions, did I forget anything
[How to set up a git environment.pdf](https://github.com/CoronaHakab/CoronaHakabModel/files/4365159/How.to.set.up.a.git.environment.pdf)

**Comment by TheZorcane** [comment]
can we close this?

**Comment by omri312** [comment]
Closing
