### ISSUE TITLE
Implement simple F (magic) function

### ISSUE THREAD

**Issue by omri312** [CoronaHakab/CoronaHakabModel#211]
**Point of contact:** Tal Nissan Cohen, Ben Avrhamai.

**Implementation Note:** This should be a module by itself, and should be easy to replace (as it will change be prone to changes in the future).
Talk to Ben about making the matrix use your function.

Few steps:
### **Implement V,W values encoding**
F should recieve 2 int values (32 bits), call them v,w.
These values should encode a set of parameters - say:
v = (v1, v2, ..., vn) and w = (v1, v2, ..., vm).
We would like to create an encoding that transforms between the seperate parameters form, and the single value 32bit form.
_Implementation suggestion_
Use bit encoding - meaning you denote first X bits to parameter 1, then Y bits to parameter 2, etc.
You will recieve upper limit for each parameter.

### **Implement the F function**
You should recieve v,w, when -
- v is a single parameter (v = (v1) )
- w is 3 parameters (w = (w1, w2, w3)

F will also hold a 4-dimensional array "probability_array" of values between 0 and 1.

The function should -
- If v value is 0 - return 0.
- If v is other than 0 -
-- return probability_array[v1][w1][w2][w3] (the probability at the index according to the parameters).

### **Values to start with**
v1 range - up to 200.
w1,w2,w3 - up to 20 each.
probability_array - 200 X 20 X 20 X 20
probability_array[a][b][c][d] =(a+b+c+d) / (200 + 20 +20 +20)
( This will make the table linarly grow from 0 to 1).

**Comment by bentheiii** [comment]
It appears simple bit-wise operations don't work so well on floats. The best solution I can see right now is to cast it to a 4-char array. This however binds us to W dividing into four 256-option variables, is this OK?
