### ISSUE TITLE
Is TOX worth the trouble?

### ISSUE THREAD

**Issue by bentheiii** [CoronaHakab/CoronaHakabModel#214]
I think it's high time we decide whether TOX remains a part of the project.

**Comment by bentheiii** [comment]
My two big reasons to remove TOX:

1. As far as I can gather, there are two kinds of commits in this project: The kind where the writer didn't bother running TOX (no judgement, certainly not from me), and the kind where the writer ran tox, and changed a whole mess of files unrelated to the commit in the process
 This causes a lot of confusion and difficulty reading commits.
2. TOX doesn't offer any advantage that pycharm's built-in linter couldn't tell us already. Run ctrl+alt+L and all of TOX's problems will fix themselves (run ctrl+alt+shift+L and you get a pretty customizable dialoge)

**Comment by meirhalachmi** [comment]
NO :)

**Comment by bentheiii** [comment]
Alright's I'm giving this issue a deadline of tomorrow afternoon for someone to convince us not to delete TOX

**Comment by meirhalachmi** [comment]
![tox](https://user-images.githubusercontent.com/42615120/79200986-ff54ac00-7e3f-11ea-9530-cffc2d6f06c8.jpeg)

**Comment by benglewis** [comment]
Why not configure Tox to automatically run on a git hook on our machines so that no one isn’t running it? I much prefer the clean code...

**Comment by benglewis** [comment]
This looks handy to do that:
https://pypi.org/project/submarine-githooks/
I’m happy to configure it.

**Comment by meirhalachmi** [comment]
@benglewis Judas.

**Comment by bentheiii** [comment]
this doesn't address the second concernt, in which the code isn't cleaner by any measure...

**Comment by benglewis** [comment]
?
@bentheiii I disagree... See here:https://github.com/CoronaHakab/CoronaHakabModel/pull/199/files

**Comment by bentheiii** [comment]
all of the changes mentioned here can be fixed just as well by pressing ctrl+alt+L  in pycharm
