### ISSUE TITLE
Parasymbolic Matrix .Total function Bug

### ISSUE THREAD

**Issue by tal-nc** [CoronaHakab/CoronaHakabModel#238]
I have noticed that some times the parasymbolic .total() function returns the wrong value.
I suspect that this is caused either from a rounding bug (summing lots of doubles) or from a bug at parasymbolic. 
This can be noticed when creating a synthetic matrix, with an easy-to-calculate total, and comparing to the the given result, or by calculating its total using numpy, and comparing to the matrix.total() output.
The matrix.total() is being used to calculate the normalization factor on any version using the Parasymbolic matrix. 
This bug results in an incorrect normalization.

![code](https://user-images.githubusercontent.com/62341091/79322000-e23ddd00-7f14-11ea-918c-0744e32f0e6e.PNG)

![output](https://user-images.githubusercontent.com/62341091/79322011-e5d16400-7f14-11ea-9fe7-bfb230336e0a.PNG)

**Comment by tal-nc** [comment]
![image](https://user-images.githubusercontent.com/62341091/79329341-4ca84a80-7f20-11ea-87a8-b53ebd0f6d44.png)

סכימה עדיפה למקרה שהמטריצה דלילה
גם במקרה הזה יש הבדל לא זניח לעיתים בין הסכום האמיתי לסכום שמתקבל מ
matrix.total()

**Comment by bentheiii** [comment]
please provide a minimal working example I can run,test and debug

**Comment by tal-nc** [comment]
https://github.com/CoronaHakab/CoronaHakabModel/tree/parasymbolic-total-test

this branch contains a - parasymbolic_total_test.py file in tests.
