### ISSUE TITLE
Make agents go into either school or work

### ISSUE THREAD

**Issue by omri312** [CoronaHakab/CoronaHakabModel#239]
Agents used to be able to be both in school (as a teacher) and at work.
We made a "patch" in cricles_generation where after allocating workers and teachers, teachers are removed from the workforce (see as a part of PR https://github.com/CoronaHakab/CoronaHakabModel/pull/202).
This is problematic because when teachers are removed from the workforce, we remain with an amount of workers that is not as we entered.

**Recomended Implementation:**
Have different pools in the begining of the generation for workers and for teachers. Then take the agents from the relevant pool.

**Comment by tal-nc** [comment]
i think that @rlfreiman already fixed this problem in his PR

**Comment by rlfreiman** [comment]
I think this was fixed by assigning workforce and only then switching some of them to teachers

**Comment by meirhalachmi** [comment]
This was done as a part of the original issue. 
Closed.
