### ISSUE TITLE
Add sanity check - all values in w are probabilities

### ISSUE THREAD

**Issue by omri312** [CoronaHakab/CoronaHakabModel#241]
Note that this is only for 3.5.

All values in W **After Normalization** should be  negative, as they are ln(1-p), where p is a probability.
Also, all values in the containgusness vector all values should be probabilities, i.e. between 0 and 1.

Add checks in the code (in matrix creation, in updating, and/or in the matrix itself), that makes sure these values aren't accidently something else.

If during the checks we find that it does happen - please open a bug with the details and contact me (Omer).

**Comment by tal-nc** [comment]
the normalization should take care of it.
currently those values are possibly higher than 1 during matrix creation and this is ok.
as long as the normalization remains as it is now, the only thing that matter during the matrix creation is the ratio between them

**Comment by tal-nc** [comment]
A good sanity check could be to make sure that W[i,j] = W[j,i] for all i,j.
this is quite heavy, so it should only be done when explicitly asked to.

**Comment by rlfreiman** [comment]
bug found.
weekly/daily connections are randomly chosen but are not mirrored. A could meet B daily while B could meet A weekly (and connection strength would be 1/7).
I'll make a bugfix branch.
