### ISSUE TITLE
Add sanity checks - can't have 0 time for state

### ISSUE THREAD

**Issue by omri312** [CoronaHakab/CoronaHakabModel#247]
We want to not allow inserting 0 as a time for a state,
Or insert a distribution of times where 0 is possible.

Make a check that return an error to the user if he accidently inserted that.

**Comment by bgmoshe** [comment]
It might solve #216 
We need to compare the results in this to the monte-carlo

**Comment by denzo9** [comment]
The default probabilities in consts allow for 0, so they need to be changed
