### ISSUE TITLE
Integrate probability of infecting

### ISSUE THREAD

**Issue by omri312** [CoronaHakab/CoronaHakabModel#28]
The simulation should consider what is the probability that a person will infect new people when they are related (a person is less infectious when he only got sick, and much more when he has symptoms).

The probability of infecting should be determined by the state of the agent,
then inserted to the vector "v" as a probability.

**Comment by omri312** [comment]
We decided that for now we will implement it this way -
Each step, calculate each cell in v - 1 in probability p, 0 otherwise; When p is the probability of infectiousness of an agent, between 0 and 1.

**Comment by tal-nc** [comment]
i have done so and pushed. however, it seems to be as this isn't good enough. the simulation collapses very quick even though r0 is updated accordingly. it looks like rolling 1 number for each agent each turn aint good enough. we will probably have to include the full solution for the mvp, and not only the patch.
