### ISSUE TITLE
Complete the machine state for the mvp

### ISSUE THREAD

**Issue by omri312** [CoronaHakab/CoronaHakabModel#48]
The state machine that we would like is -
1 - Susceptible - not infecting.
2 - Silent - got infected, not infecting yet.
after 1 day, I'm with 50% chance to become either:
2 -  asymtpomatic - 25% infectious.
3 - symptomatic - 75% infectious.
After 3 days more, turn into either - 
4 - Recovered (with 95% chance) - cannot get infected anymore.
5 - Dead (with 5% chance).

**Comment by tal-nc** [comment]
done
