### ISSUE TITLE
New-New agent state machine

### ISSUE THREAD

**Issue by omri312** [CoronaHakab/CoronaHakabModel#63]
We would like to update the state machine yet again!
update it to this diagram, which also conatins the parameters needed for each state -

![WhatsApp Image 2020-03-23 at 21 51 28](https://user-images.githubusercontent.com/18164690/77361863-b5086f80-6d58-11ea-8116-84ca7ff45e01.jpeg)

**Comment by bentheiii** [comment]
Is this necessary for MVP?  Doing this right would require to overhaul the entire way we handle states (we should do this already, but top priority will require a mess)

**Comment by omri312** [comment]
What remains here - make sure that this works well, and that we're not too far from the previous results we had

**Comment by omri312** [comment]
Done
