### ISSUE TITLE
Export and import the matrix from a file

### ISSUE THREAD

**Issue by omri312** [CoronaHakab/CoronaHakabModel#69]

**Comment by mor-m-shemesh** [comment]
In the current implementation of the matrix - a scipy sparse lil_matrix - there is an easy way to import/export to file - npz files.

When implementing a new matrix - it would be beneficial to implement a serialization of the structure in the CPP implementation itself.

**Comment by mor-m-shemesh** [comment]
https://github.com/CoronaHakab/CoronaHakabModel/pull/86
export/import matrices using npz format from scipy

**Comment by omri312** [comment]
Done
